// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SA.Infrastructure.Contexts;

#nullable disable

namespace SA.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20251123104806_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SA.Domain.Entities.Service", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("TariffId")
                        .HasColumnType("bigint")
                        .HasColumnName("tariff_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("TariffId")
                        .HasDatabaseName("ix_services_tariff_id");

                    b.ToTable("services", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<long>("TopicId")
                        .HasColumnType("bigint")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("TopicId")
                        .HasDatabaseName("ix_subscriptions_topic_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Tariff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<long>("SubscriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_tariffs");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_tariffs_subscription_id");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Topic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric")
                        .HasColumnName("rating");

                    b.HasKey("Id")
                        .HasName("pk_topics");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_topics_name");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("SA.Domain.Entities.Service", b =>
                {
                    b.HasOne("SA.Domain.Entities.Tariff", "Tariff")
                        .WithMany("Services")
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_tariffs_tariff_id");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("SA.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("SA.Domain.Entities.Topic", "Topic")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_topics_topic_id");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SA.Domain.Entities.Tariff", b =>
                {
                    b.HasOne("SA.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Tariffs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariffs_subscriptions_subscription_id");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SA.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Tariffs");
                });

            modelBuilder.Entity("SA.Domain.Entities.Tariff", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("SA.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
